import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import SideNav from 'components/SideNav.js'
import Item from '@/components/Item'
import buttery from "public/buttery.jpeg"
import sterling from "public/sterling.jpeg"
import yaleBowl from "public/yalebowl.jpeg"
import handsomeDan from "public/handsomedan.jpeg"
import Web3 from "web3";
import Yale from '../conect/Yale'
import { getContract } from "../conect/yaleContract";
import { useState, useEffect } from "react";
import { useWeb3React } from "@web3-react/core";
import Wallet from '@/components/Wallet'


/*export async function getStaticProps(context){

	try {
		const web3 = new Web3(`wss://mainnet.infura.io/ws/v3/${process.env.INFURA}`)

		const yaleContract = new web3.eth.Contract(Yale.abi,'0xc57c5ac5cdbfe5d77a4dd539205bc07df0930533')

		
        var owner = await yaleContract.methods.owner().call()

        var data = {
			total:{
				mid:0,
				share:0,
				you:0,
				per:0
			},
            baseMult:1
		}


		return {
			props: {
				data
			}
			
		}
	}catch(error){
		console.log(error)
	}
	return[]
}*/


export default function Contract() {

    
    const [balance, setBalance] = useState(1);
    const [rate, setRate] = useState(1);
    const [busiStats, setBusiStats] = useState([{}]);
    const [userStats, setUserStats] = useState({});
    const [mintable, setMintable] = useState(1);
	  const [loaded, setLoaded] = useState(false);
    const web3reactContext = useWeb3React();

    //console.log("WHat is this: ", web3reactContext)
    
    useEffect(() => {
        // setShowModal(true)
        init();
        if (window.ethereum) {
            window.ethereum.on("accountsChanged", function (accounts) {
                reload();
            });
            init();
        } else {
            init();
        }
    }, []);
	
	
	async function init(){
        console.log("hitting init")
        console.log("account: ", web3reactContext.account)
		try {
        
      if (web3reactContext.account != undefined) {
				const YaleContract = await getContract(
					web3reactContext.library,
					web3reactContext.account
				);

				
				const balance = parseInt(await YaleContract.balanceOf(web3reactContext.account))

        var busiData = [
          {mult: 0, quantity:0, rate:0, time:0},
          {mult: 0, quantity:0, rate:0, time:0},
          {mult: 0, quantity:0, rate:0, time:0},
          {mult: 0, quantity:0, rate:0, time:0}
        ]
        
        var tmpRate = 0
        
        for(var i = 0; i<4; i++) {
          var tmpUserStats = await YaleContract.Users(web3reactContext.account,0)
          //console.log("Rate: ", parseInt(tmpUserStats[0]))
          busiData[i]['mult'] = parseInt(tmpUserStats[0])
          busiData[i]['quantity'] = parseInt(tmpUserStats[1])
          busiData[i]['rate'] = parseInt(tmpUserStats[2])
          busiData[i]['time'] = parseInt(tmpUserStats[3])

          tmpRate += (busiData[i]['mult'] * busiData[i]['rate'])
        }

				if (busiData[0]['time'] != 0) {
          var tmpMintable = parseInt(await YaleContract.mintableCoin())
          setMintable(tmpMintable)
        }
				
        console.log("Hitting here")
        setBalance(balance)
        setRate(tmpRate)
        setBusiStats(busiData)
				setLoaded(true)
			}
			else {
        setBalance(0)
        setRate(0)
        setBusiStats([
          {mult: 0, quantity:0, rate:0, time:0},
          {mult: 0, quantity:0, rate:0, time:0},
          {mult: 0, quantity:0, rate:0, time:0},
          {mult: 0, quantity:0, rate:0, time:0}
        ])
        setLoaded(true)
			}
    } catch (error) {
        console.log(error);
    }
	}
	
  function reload(){
		window.location.reload(false);
	}

  async function joinGame() {
        
    const YaleContract = getContract(
        web3reactContext.library,
        web3reactContext.account
    );

    
    try {
      let joining = await YaleContract.joinGame();

      await joining.wait();

      init();
    }
    catch (error) {
      console.log(error)
    }
}
    
    

  return (
    <>
      <Head>
        <title>IdleYale</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
    <>
      
    {loaded ?
      <div>  
        <div className='flex flex-row justify-between'>
          <SideNav highlight={"Yale"}> </SideNav>
          
          <div className="flex flex-col w-full h-fit bg-[url('../public/yalebg.jpeg')] bg-cover md:ml-[250px] gap-[75px] pt-16">
            
            <Wallet {...{ init, reload }}></Wallet>
            
            <h2 className='text-white text-2xl text-center'>Balance: {balance}</h2>
            
            {busiStats[0]['time'] ?
              <h2 className='text-white text-xl text-center'>Rate: {rate} tokens / min</h2>
            :
            <>
              {web3reactContext.account != undefined ?
              <button className='bg-[#dadada] w-1/3 self-center rounded-md text-black text-xl text-center p-4' onClick={joinGame}>Join game!</button>
              :
              <h2 className='text-white text-xl text-center'>Connect Wallet Above!</h2>
              }
            </>
            }
            <Item title="Buttery" desc="Rate: 1 token / minute" image={buttery}></Item>
            <Item title="Sterling Library" desc="Rate: 10 tokens / minute" image={sterling}></Item>
            <Item title="Yale Bowl" desc="Rate: 100 tokens / minute" image={yaleBowl}></Item>
            <Item title="Handsome Dan" desc="Rate: 1,000 tokens / minute" image={handsomeDan}></Item>

          </div>
        </div>

      </div> 

      :
      <>
      
      <Wallet {...{ init, reload }}></Wallet>
      <a>Something went wrong</a>

      </>
    }

    </>
   
    </>
  )
}
