import Head from 'next/head'
import Image from 'next/image'
//import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

//const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>IdleIvy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Goldman&display=swap" rel="stylesheet" />
      </Head>
      <div className='flex flex-col items-center font-display bg-gradient-to-b from-[#272727] to-[#797979] h-screen justify-center'>
          <div className='mb-[20px]'>
            <h2 className='text-white font-semibold text-[90px]'>IdleIvy</h2>
          </div>

          <div className='flex flex-row items-center gap-[90px]'>
            {/*Harvard Version*/}
            <div className='flex flex-col items-center'>
              <h2 className='text-white font-semibold text-[40px] mb-[20px]'>Harvard</h2>
              <Link href={"/"}>
                <button type="button" className="text-3xl text-white bg-[#BD1717] px-[35px] py-[10px] w-[250px] h-[100px] rounded-full outline outline-white outline-[7px]"> 
                  Locked
                </button>
              </Link>
            </div>

            {/*Yale Version*/}
            <div className='flex flex-col items-center'>
              <h2 className='text-white font-semibold text-[40px] mb-[20px]'>Yale</h2>
              <Link href={"./contract"}>
                <button type="button" className="text-3xl text-white bg-[#202B64] px-[35px] py-[10px] w-[250px] h-[100px] rounded-full outline outline-white outline-[7px]"> 
                  Click here to play!
                </button>
              </Link>
            </div>

            {/*Princeton Version*/}
            <div className='flex flex-col items-center'>
              <h2 className='text-white font-semibold text-[40px] mb-[20px]'>Princeton</h2>
              <Link href={"/"}>
                <button type="button" className="text-3xl text-white bg-[#FF8000] px-[35px] py-[10px] w-[250px] h-[100px] rounded-full outline outline-white outline-[7px]"> 
                  Locked
                </button>
              </Link>
            </div>
          </div>
        

      </div>
    </>
  )
}
