import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import SideNav from 'components/SideNav.js'
import Item from '@/components/Item'
import buttery from "public/buttery.jpeg"
import Leaderboard from '@/components/Leaderboard'
import Link from "next/link";


export default function YaleLeaderboard() {
  return (
    <>
      <Head>
        <title>IdleYale</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Goldman&display=swap" rel="stylesheet" />
      </Head>
      
      
    
      <div className="flex flex-col w-full h-screen bg-[url('../public/yalebg.jpeg')] bg-cover">
        <Link href="./contract" className='font-display text-[30px] text-white mt-[20px] mb-[30px] ml-[20px]'>Back</Link>
        <Leaderboard></Leaderboard>
      </div>
      
   
    </>
  )
}