import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import SideNav from 'components/SideNav.js'
import Item from '@/components/Item'
import buttery from "public/buttery.jpeg"

export default function Yale() {
  return (
    <>
      <Head>
        <title>IdleYale</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <div>  
        <div className='flex flex-row justify-between'>
          <SideNav highlight={"Yale"}> </SideNav>
          
          <div className="flex flex-col w-full bg-[url('../public/yalebg.jpeg')] bg-cover md:ml-[250px] gap-[75px]">
            
            <Item title="Buttery" desc="Use 1,000 tokens to increase rate by 0.1 tokens" image={buttery}></Item>
            <Item title="Sterling Library" desc="Use 10,000 tokens to increase rate by 0.5 tokens" image={buttery}></Item>
            <Item title="Yale Bowl" desc="Use 100,000 tokens to increase rate by 1.0 tokens" image={buttery}></Item>
            <Item title="Handsome Dan" desc="Use 1,000,000 tokens to increase rate by 5.0 tokens" image={buttery}></Item>

          </div>
        </div>

      </div> 
   
    </>
  )
}
