import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import SideNav from 'components/SideNav.js'

export default function Yale() {
  return (
    <>
      <Head>
        <title>IdleYale</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
          <SideNav highlight={"Yale"}> </SideNav>
          
          <div className="flex flex-col bg-[url('../public/yalebg.svg')] bg-contain h-screen items-center justify-center ml-[250px]">
            <div className='flex flex-row'>
              <img className="h-[130px] w-[250px] mr-[60px] rounded-full outline outline-white outline-[5px]" src="../sterling.svg"></img>
              <div className='flex flex-row w-[850px]'>
              <button id="upgrade_buttery" type="button" className="z-10 bg-[#202B64] h-[130px] w-[250px] rounded-full outline outline-white outline-[5px]">
                <div>
                  <h2 className={`text-4xl text-white`}>
                    Upgrade
                  </h2>
                </div>
              </button>
              <div className='fixed text-center z-0 bg-gradient-to-b from-[#272727] to-[#797979] h-[130px] w-[850px] rounded-full outline outline-white outline-[5px]'>
                <div className='relative top-[20%] left-[15%]'>
                  <h3 className={`text-3xl text-white justify-center mb-[10px]`}>Sterling Library</h3>
                  <h4 className={`text-2xl text-white justify-center`}>Use 10,000 tokens to increase rate by 0.5 tokens</h4>
                </div>
              </div>
              </div>
            </div>

            
          </div>
   
    </>
  )
}
