name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [3.8, 3.9]

    steps:
        # Install requirements
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "./FlaskAPI/requirements.txt"
          update-pip: "true"
          update-setuptools: "true"
          update-wheel: "true"
      # Begin testing.
      # Run pytest backend tests.
      - name: backend tests
        run: pytest -rm
