name: test_db.py
run-name: ${{ github.actor }} is testing the backend with Pytest

on: [push]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - run: pytest -rm
